import matplotlib.pyplot as plt

def plot_energy_mix(t, x, title):
    """
    Plot the evolution of energy source shares over time.

    This function generates a line plot showing the fraction of electricity 
    generated by different energy sources over time, based on numerical 
    simulation results from the replicator dynamics model.

    Parameters
    ----------
    t : ndarray, shape (m,)
        Array of time points corresponding to the simulation results.
    x : ndarray, shape (m, 5)
        Array of energy shares at each time point. Each column corresponds 
        to a specific energy source in the following order:
        ["Fossil", "Nuclear", "Wind", "Solar", "Hydro"].
        Each row should sum to 1 (normalized energy shares).
    title : str
        Title of the plot to be displayed.

    Returns
    -------
    None
        The function displays a plot using Matplotlib. No values are returned.

    Notes
    -----
    - The y-axis represents the share of total electricity generation 
      (values between 0 and 1).
    - The function assumes that `x` has exactly five columns, each corresponding 
      to a predefined energy source.
    """
    labels = ["Fossil", "Nuclear", "Wind", "Solar", "Hydro"]

    for i in range(5):
        plt.plot(t, x[:, i], label=labels[i])

    plt.xlabel("Time")
    plt.ylabel("Share of electricity generation")
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()
